language: c
compiler:
  - clang
  - gcc

os:
  - linux
  - osx
before_install:
  - echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
  - git clone https://github.com/EdHurtig/libimu-private.git libimu
  - git clone https://github.com/sstephenson/bats.git
  - cd bats
  - ./install.sh /usr/local
  - cd ..

before_script:
  - ls -la
  - pwd
  - cd libimu && make && make install && cd ..
  - $CC --version

script:
  - $CC --version
  - ls -la
  - pwd
  - make && make install
  - ./test.bats
